          SUBROUTINE particle_arrays

          use indeces
          use parparam

          allocate (ltheta(npt2))
          allocate (iprecip(npt2))
          allocate (pa(npt2))
          allocate (mu_m(npt2))
          allocate (mu_m2(npt2))
          allocate (vpar0(npt2))
          allocate (vpar1(npt2))
          allocate (vpar2(npt2))
          allocate (pa_check(npt2))
          allocate (penergy0(npt2))
          allocate (Bo_p(npt2))
          allocate (dB1(npt2))
          allocate (dB2(npt2))
          allocate (r_p(npt2))
          allocate (ro_p(npt2))
          allocate (theta_p(npt2))
          allocate (nu_p(npt2))
          allocate (h2p(npt2))
          allocate (mu0_p(npt2))
          allocate (mu1_p(npt2))
          allocate (mu2_p(npt2))
          allocate (h1p_1(npt2))
          allocate (h1p_2(npt2))
          allocate (e1p_1(npt2))
          allocate (e1p_2(npt2))
          allocate (den_grid(n21))
          allocate (j1p_grid(n21))
          allocate (sm_grid(n21))
          allocate (den_temp(n21))
          allocate (j1p_temp(n21))
          allocate (ratio_grid(n21))
          allocate (den_grid0(n21))
          allocate (mu_grid(n21))
          allocate (mu_grid2(n21))
          allocate (pint_temp(n_int))
          allocate (x1_temp(n_int))
          allocate (F(n_int))

          END SUBROUTINE particle_arrays
